### ISSUE TITLE
Privacy Badger Blocking Site to load

### ISSUE THREAD

**Issue by dkotama** [oscartbeaumont/spotistats#7]
**Prequisite :** 
User have Privacy Badger Plugin Installed

**Expected :** 
Site load without error

**Current result:** 
![image](https://user-images.githubusercontent.com/5332757/175238773-96e8bb0f-3e39-46d1-9841-c8c36ff87448.png)

**Solving:** 
Disabling privacy badger enabled the sites,
but the errors should tells user to turn off instead to re-login

**Comment by oscartbeaumont** [comment]
I can add a warning but in no way can I detect if privacy badger is installed. I had this issue myself and it's annoying but there is nothing I can do due to how browser plugins work.

**Comment by dkotama** [comment]
> I can add a warning but in no way can I detect if privacy badger is installed. I had this issue myself and it's annoying but there is nothing I can do due to how browser plugins work.

Warning or steps to fix  would be awesome.
